travis:
  secure:
    BINSTAR_TOKEN: VGSLpTij2T++oJEiVpunS4I3kLlWOH0uz3jjXBPPGx58by049p0Fx6yMWp06VejMPuFaJoJuDvLEmz9a/F7h0Jp4Zac3Ij2+uaofJXBqKzE4uFMuB0YIkJlrFuy/BFoVU3D9Fu4l1cGei/zWXGYnrt+6P+CZMEvrETvMfac1h6N1/5Dt18fG40Cl05HUos+PPZ7AZR9EiGtE+8iD4MpWn94G2N3iYHXFqd0hPEEbS78UFXjeAENw9e+whqBRDdcDYWZhPiQsRJ+BZHQOp043sPe72TgBAnWI3TMOP+aIf9NCo/P6UelRKsVJAWOkGDn4GP+OpEhaW9gHYjguGNvOm04Njh04GCVvEjZiqG+MOQ4HE2hw5lEoqhgcgg99TVsioSPan1AfAvAPk1I30/HbV+4eF3GB5Vdq2QSHblZ5rz0XRWFXRYsuhfdg3HayWj/xYivv8rKBtw7fRed9DYcii9ISHZVnKkk/4IvXsfzuQFIPL/NRyOfldCgpnSXSaliWMkVeVfFmfvByfbTgZST7Y+AbqmXhs/qHXhAf6qkBpQVwAR99rAQ2fYrvPF3lZzHD3uIz8v8MireGy+C0jDOCK2wC0jFxAXU8iL5zZRjUUuBoBJ735KduJxobw80YAmUynWNDwHmoqTQMokBlA3RlxnN3FxR4EIBHX+BGIV7YO+s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
